# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b724d8213246aadbaab6ca8469c5293f98507cb05adb5cb1acb292f89c8c3bc8cae4efa05bc55c4d182e5f4b4d76e6ef865ca1c3e670b64b216006a6505dcec

test:
  secret_key_base: c5b5e1e23f70f133cb601aaa63739d900f8a6047e5585c4154544fa212397c7518d2be3ef612f2246f374be927e252b26eb8350b97a2011e24258f3852c971d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
